name: sentry_app
description: "Sentry - Control de acceso seguro a eventos."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.4

dependencies:
  excel: ^4.0.6
  file_picker: ^11.0.2
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^8.0.2
  mobile_scanner: ^7.2.0
  qr_flutter: ^4.1.0
  google_sign_in: ^6.2.1
  supabase_flutter: ^2.12.4
  geolocator: ^13.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/Llamasgif.gif
